// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIU-Jqdy7cmureLJQZ_pIkstQO9emuRA',
    appId: '1:5681428371:web:4e51fd22ca7dc005fc9a66',
    messagingSenderId: '5681428371',
    projectId: 'todo-firestore-36d62',
    authDomain: 'todo-firestore-36d62.firebaseapp.com',
    storageBucket: 'todo-firestore-36d62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVCcBrFs2aSz3fXIsAde6VbyfdIr0g84',
    appId: '1:5681428371:android:9a1149e47aef4033fc9a66',
    messagingSenderId: '5681428371',
    projectId: 'todo-firestore-36d62',
    storageBucket: 'todo-firestore-36d62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6CTL3PGaXwNDS47p9XF258u-hwEEex0',
    appId: '1:5681428371:ios:f9603c3aae288d69fc9a66',
    messagingSenderId: '5681428371',
    projectId: 'todo-firestore-36d62',
    storageBucket: 'todo-firestore-36d62.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6CTL3PGaXwNDS47p9XF258u-hwEEex0',
    appId: '1:5681428371:ios:f9603c3aae288d69fc9a66',
    messagingSenderId: '5681428371',
    projectId: 'todo-firestore-36d62',
    storageBucket: 'todo-firestore-36d62.appspot.com',
    iosBundleId: 'com.example.toDo',
  );
}
